services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U crm_user -d crm_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
